version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chowly-demo-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - demo-network
networks:
  demo-network:
    external: true
