version: '3.5'
services:
  web:
    build: .
    container_name: chowly-backend-demo
    image: python:3.8
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
    networks:
      - demo-network
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chowly-demo-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - demo-network
networks:
  demo-network:
    name: demo-network