name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Manually Triggered Build"
        required: false

env:
  REGISTRY: registry.digitalocean.com/kss11b
  IMAGE_PREFIX: chowly-demo
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
          with:
            node-version: '21.4.0'
        - run: npm ci
        - run: npm run build

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to DigitalOcean Container Registry
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Next.js App Image
        uses: docker/build-push-action@v2
        with:
          context: ./chowly-demo-frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/chowly-front-end:latest

      # Build and push Flask App Image
      - name: Build and push Flask App Image
        uses: docker/build-push-action@v2
        with:
          context: ./chowly-demo-backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/chowly-back-end:latest
